seed: 42

output_dir: path/to/output_dir
checkpoint_dir: path/to/checkpoint_dir
split_dir: path/to/split_dir

shared_split_dir: path/to/shared_split_dir #meaning the prefixed split csvs
canonical_split_source: resnet_metadata

metadata_csv: path/to/shared_split_dir /metadata.csv

batch_size: 32
num_workers: 4
epochs: 100
lr: 1.0e-4
weight_decay: 1.0e-4

val_size: 0.10
test_size: 0.10
 
use_weighted_loss: true
use_amp: false
device: auto

pretrained: true
image_size: 224

wandb_project: whale-classification
wandb_run_name: resnet18_50_to_350hz_bandwidth

use_wandb: true
best_metric_name: val_best_f1 #choose best metric for you
default_eval_threshold: 0.5
use_best_threshold_during_training: false
